version: '3.9'

services:
  cas-sso-discord-bot:
    container_name: CAS-SSO-Discord-Bot
    image: bepolytech/ulbdiscordbot:dev-2.0.0-alpha5  # or version like :1.2
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    env_file:
      - .env
    #volumes:
    #  - ./:/app
    network_mode: host
    restart: unless-stopped # or unless-stopped or on-failure
#    #! Comment this below if using Google Sheets as a database
#    depends_on:
#      db:
#        condition: service_healthy
#
#  #! --- Comment this below if using Google Sheets as a database ---
#
#  ## Postgres
#  database:
#    image: postgres:15-alpine # version ?
#    container_name: DB_CAS-SSO-Discord-Bot
#    env_file:
#      - .env
#    volumes:
#    - ./db-data:/var/lib/postgresql/data:cached
#    expose:
#     - "${DB_PORT}" # 5432 ?
#    restart: always
#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  ## MySQL
#  database:
#    image: mysql:alpine # version ?
#    container_name: DB_CAS-SSO-Discord-Bot
#    env_file:
#      - .env
#    volumes:
#      - ./db-data:/#?TODO
#    expose:
#      - "${DB_PORT}" # ?
#    restart: always
#  
