version: '3'

services:
  CAS-SSA-DISCORD-BOT:
    image: bepolytech/cas-sso-discord-bot:latest # or version like :1.2
    container_name: CAS-SSO-Discord-Bot
    #build:
    #  context: .
    #  image: cas-sso-discord-bot
    #  dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/usr/src/cas-sso-discord-bot
    restart: always # or unless-stopped or on-failure
