name: Test docker image build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  docker:
    name: docker build test
    runs-on: ubuntu-latest
    permissions:
      #packages: write
      contents: read
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Extract VERSION
        id: get_version
        run: |
          FULL=$(cat VERSION)
          MAJOR=$(echo "$FULL" | cut -d. -f1)
          MINOR=$(echo "$FULL" | cut -d. -f1,2)

          echo "version=$FULL" >> $GITHUB_OUTPUT
          echo "minor=$MINOR" >> $GITHUB_OUTPUT
          echo "major=$MAJOR" >> $GITHUB_OUTPUT

          echo "🔢 Version: $FULL"
          echo "🔢 Minor: $MINOR"
          echo "🔢 Major: $MAJOR"

      - name: ⚙️ Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: 🛠 Build docker image (no push) for GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false # only test build
          load: false # only test build
          outputs: |
            type=docker,platform=linux/amd64 # action runner is amd64 so we can load only this one
            type=local,dest=./output-arm64,platform=linux/arm64
          tags: ${{ github.actor }}/${{ github.repository }}:test-build # only test build
          labels: |
            org.opencontainers.image.description="BUILD TEST"
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.get_version.outputs.version }}
          build-args: |
            VERSION=${{ steps.get_version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 🔍 Check Docker images are built
        run: |
          echo "🔍 Checking if the Docker images are built..."
          # Check if the images exist locally
          docker images
      
      #-
      #  name: Test docker image
      #  run: |
      #    docker run --rm ${{ github.actor }}/${{ github.repository }}:test-build

      - name: ✅ Done (no publish)
        run: echo "✅ Docker image built successfully, not pushed."

